### PR TITLE
Migrate to LabelSync Manager

### PR DESCRIPTION
**Pull request by maticzav**
Hi :wave:,

I have created a new version of LabelSync, which now works as a Github App. Because of this, your workflow should be easier and faster, as the app comments in real time to pull requests outlining changes, and doesn't rely on CircleCI anymore. I hope this could potentially save you a lot of time and evolve into something that would significantly reduce your burden in managing repositories and projects.

I have already renamed this repository, as the new service fetches configuration from `prisma-labelsync` repo, and modified the code to conform to the latest spec. What remains is installing an [app](https://github.com/apps/labelsync-manager).

I'd be thrilled to hear your thoughts and suggestions, and even happier to answer your questions 🙂 

> https://github.com/maticzav/label-sync

### CODE REVIEW

**Comment by janpio** [comment]
Thanks, will look into this after the holidays.

**Comment by jasonkuhrt** [comment]
fwiw Labs team is trying it out over here https://github.com/prisma-labs/prisma-labs-labelsync

**Comment by jasonkuhrt** [comment]
I'm not seeing any bot comment on the the PR? https://github.com/prisma-labs/prisma-labs-labelsync/pull/2.

But when I commit to master it works instantly :D

**Comment by maticzav** [comment]
@jasonkuhrt let me look into that. Very strange!

**Comment by janpio** [comment]
Replaced by https://github.com/prisma/prisma-labelsync/pull/189

**Pull request closed without merging**
