### PR TITLE
Migrate to LabelSync

### PR DESCRIPTION
**Pull request by janpio**
replaces https://github.com/prisma/prisma-labelsync/pull/189

### CODE REVIEW

**Comment by janpio** [comment]
Something is funky here @maticzav - in theory @labelsync-manager should have access to all repos in our org per https://github.com/apps/labelsync-manager. 

image

Or am I missing something?

**Comment by maticzav** [comment]
hey hey, yeah the problem is the `prisma/` part in front of every repository. I can fix the PR by the end of the day.

**Comment by maticzav** [comment]
@janpio I think I messed something up. I changed the names, but some are still missing. We could also jump on a call tomorrow if you prefer.

**Comment by janpio** [comment]
No, that is perfect - these names are indeed not updated yet (we renamed the repos not to long ago). Sometimes this works with redirects, here it does not seem to which might actually be a good thing as it forces us to clean up 👍 (You might want to take this into account in the error message though)

**Comment by janpio** [comment]
Yay, got it to work @maticzav!

Took me some time to understand that I need to run the precommit hook manually if I just change things here in Github UI - that is the primary way I do things. Maybe the app can take care of that as well?

The "Unconfigured labels." (note the dot at the end - that looks like a bug) will be a lot of visual noise in each PR and make it hard to find the actual changes. Maybe hide that behind a `<details>` so I can only look at it if I want?

Bigger problem:
The "changed labels" of the first repos are concerning though - those are all Prisma 1 repositories we have not touched for quite some time. Can I somehow find out _how_ they were changed exactly?

**Comment by janpio** [comment]
Had another look, I can not figure out what would require a change to this label:

image


image

image

**Comment by maticzav** [comment]
@janpio thank you for being so patient with my response, I didn't catch it in my notifications.

I fidgeted a bit around how label diffing works - hope it turns out well - and implemented the collapsable reports; I hope you like it!

> PS.: Thank you for bringing it up! I didn't even know that was possible. Thanks! 😄 ❤️

**Comment by janpio** [comment]
Thanks @maticzav - the `<details>` is a nice change and make this much easier to parse. I would possibly only have added it for the unconfigured ones, but this works as well.

> You have no unconfigured labels - you could make this repository strict.

This is a bit strange though and seems wrong above, right?

The "changed labels" are hidden now, but still seem to list a _lot_ of things that I am not really sure about what is being changed there - in my opinion nothing is really. ( `prisma1` is the example I looked into in detail again)

"Unconfigured labels" seems to list all labels twice now for `prisma` (but not other repos) behind the `<details>` which seems to be a bug.

**Comment by maticzav** [comment]
Alright! Firstly, man, @janpio thank you so much for all the input!

1. Yeah, that was a bug there was an `or` instead of an `and` statement in the logic. Should be good to go now.

2. For both of the above issues, I have an idea what might be causing them, I fiddled a bit with the code, I hope it fixes it, but we'll just have to try. I have made some more adjustments to make it easier for you to work with it in pull requests.

Thanks!! 😄

**Comment by janpio** [comment]
Yep, I think you got it @maticzav! That looks pretty much as expected. 
Will merge this later and see what happens when this is applied 👍

**Comment by janpio** [comment]
Hey @maticzav, possibly found another problem here: I added the `keep` label for the `specs` repo, but the comment after adding that via a commit still tells me it will be removed. Bug in the display or will this actually be removed?

**Comment by maticzav** [comment]
@janpio I am not sure I understand. It seems like you've removed the `keep` label from the configuration, though I see that you have it in the TS-files. Could you try regenerating the `labelsync.yml` file?

If you don't want to remove labels, however, you can uncheck the `removeUnconfiguredLabels` option.

**Comment by janpio** [comment]
> Could you try regenerating the labelsync.yml file?

That is the part that did not happen probably as I only edited the file via the Github UI. I probably should add a Github action which does that automatically. Or can your app also do that maybe?

**Comment by janpio** [comment]
Ok, the merge went just fine @maticzav!

I also figured out what got changed for the 4 labels for `prisma-engines`:
image

image
became
image

So indeed the description was updated - but the current comment does not show that yet. That would be a great improvement. You can possibly show that under the badge for the label with a codeblock of type `diff` for example.

**Comment by maticzav** [comment]
Awesome, I am very excited that you are finally using it. 😄 

Will add the description change notice.

**Pull request merged**
