### PR TITLE
add confidence labels for DevProd repos

### PR DESCRIPTION
**Pull request by petradonka**

### CODE REVIEW

**Comment by petradonka** [comment]
@janpio, is /labelsync needed even if I generated locally? 🤔

**Comment by janpio** [comment]
If it does not commit anything, I have confirmation that all necessary changes are taken care of. And I thought it would create a preview of what the changes would be (similar to https://github.com/prisma/prisma-labelsync/pull/270#issuecomment-1165595310) - but seems not (any more?)

**Comment by petradonka** [comment]
Oh, that's a thing! I guess not anymore - my [previous PR](https://github.com/prisma/prisma-labelsync/pull/271) from a few days ago didn't have that either

**Comment by janpio** [comment]
Ok, the action does work better now at least - but the file is indeed correct already.

Labelsync itself seems to have gone quiet :( Did you last change get applied properly?

**Comment by petradonka** [comment]
My previous PR was just disabling it for a repo - so not sure. It'd look the same both if it worked and if it did not 😄

**Comment by janpio** [comment]
Good point.

**Comment by janpio** [comment]
The previous commit that _did_ something got the comment: https://github.com/prisma/prisma-labelsync/commit/49fe3b04cbc158b30b7539590f9de3abcb0d0546

**Comment by janpio** [comment]
And the PR also got the comments: https://github.com/prisma/prisma-labelsync/pull/270

Raises the question: Why not here?

**Review by jasonkuhrt — APPROVED** [review]
LGTM!

**Comment by petradonka** [comment]
> And the PR also got the comments: #270
> 
> Raises the question: Why not here?

Unsure. I'd merge and we see? Would labelsync apply the changes straight away?

**Comment by jasonkuhrt** [comment]
Yeah, once this merges to trunk labelsync will apply the changes right away.

**Comment by petradonka** [comment]
I don't think this thing works 🤔 After merging, I'm not seeing any changes, and a comment like https://github.com/prisma/prisma-labelsync/commit/49fe3b04cbc158b30b7539590f9de3abcb0d0546#commitcomment-76903004 is also missing.

@janpio, @jasonkuhrt, do you have any theories why this is not working?

**Comment by jasonkuhrt** [comment]
Investigating, strange indeed!

**Comment by jasonkuhrt** [comment]
- https://github.com/prisma/prisma-labelsync/commit/31d7808fef421a8ee2a5c40a05c9eb8adba53a6a had no comment. The YAML is simply labels being removed. The source code change is irrelevant to LabelSync GH App. So........................Looks like a LabelSync bug? (Would not be the first time).
	- We've renamed our repos a few times, maybe that tripped up labelsync somehow (just guessing).
- The this https://github.com/prisma/prisma-labelsync/commit/522762176ba4b45fd3f0dbd1b33c09589841910a which IIUC has nothing to do with trunk commits anyways and should have no bearing on the issue we're looking at now which is trunk specific
- https://github.com/prisma/prisma-labelsync/commit/568a1b05667c8a6d1e66ea0d55c6de30b7c19167 this dep update should not matter since as mentioned only the YAML file should matter for the GH App.
- https://github.com/prisma/prisma-labelsync/commit/1b23d6b86cc05531ba2f6eaf1b3263ec56d35f24 Massive delete diff with some additions (the merge of this PR). Again the YAML is sound.

I'm strongly thinking there is a bug somewhere in all this with Labelsync.

In the past I've reached out to @maticzav who owns this product, I'll do so again on Twitter.

**Comment by jasonkuhrt** [comment]
CleanShot 2022-09-23 at 10 53 18@2x

**Comment by janpio** [comment]
https://github.com/maticzav/label-sync exists btw :D

**Comment by jasonkuhrt** [comment]
@janpio looks like a better lace to communicate!

**Comment by jasonkuhrt** [comment]
CleanShot 2022-09-27 at 14 39 58@2x

The official docs say email 🤷 So I've done that just now.

CleanShot 2022-09-27 at 14 39 48@2x

**Pull request merged**
